=== OPSILab/Cape/cape-server/service-registry/doc/service-descriptions/ServiceEntry_schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "required": [
    "serviceId",
    "name",
    "identifier",
    "issued",
    "createdByUserId",
    "serviceDescriptionVersion",
    "serviceIconUrl",
    "status",
    "supportedProfiles",
    "spatial",
    "lifeEvent",
    "businessEvent",
    "sector",
    "type",
    "thematicArea",
    "language",
    "hasCompetentAuthority",
    "humanReadableDescription",
    "serviceInstance",
    "isDescribedAt",
    "processingBases"
  ],
  "properties": {
    "serviceId": {
      "type": "string",
      "default": ""
    },
    "name": {
      "type": "string",
      "default": ""
    },
    "identifier": {
      "type": "string",
      "default": ""
    },
    "issued": {
      "type": "string",
      "default": ""
    },
    "createdByUserId": {
      "type": "string",
      "default": ""
    },
    "serviceDescriptionVersion": {
      "type": "string",
      "default": ""
    },
    "serviceIconUrl": {
      "type": "string",
      "default": ""
    },
    "status": {
      "type": "string",
      "default": ""
    },
    "supportedProfiles": {
      "type": "array"
    },
    "spatial": {
      "type": "string",
      "default": ""
    },
    "lifeEvent": {
      "type": "string",
      "default": ""
    },
    "businessEvent": {
      "type": "string",
      "default": ""
    },
    "sector": {
      "type": "array"
    },
    "type": {
      "type": "array"
    },
    "thematicArea": {
      "type": "array"
    },
    "language": {
      "type": "array",
      "items": {
        "type": "string",
        "default": ""
      }
    },
    "hasCompetentAuthority": {
      "type": "object",
      "required": [
        "prefLabel",
        "spatial"
      ],
      "properties": {
        "prefLabel": {
          "type": "string",
          "default": ""
        },
        "spatial": {
          "type": "string",
          "default": ""
        }
      }
    },
    "humanReadableDescription": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "locale",
          "description",
          "keyword"
        ],
        "properties": {
          "locale": {
            "type": "string",
            "default": ""
          },
          "description": {
            "type": "string",
            "default": ""
          },
          "keyword": {
            "type": "array",
            "items": {
              "type": "string",
              "default": ""
            }
          }
        }
      }
    },
    "serviceInstance": {
      "type": "object",
      "required": [
        "serviceProvider",
        "cert",
        "serviceUrls"
      ],
      "properties": {
        "serviceProvider": {
          "type": "object",
          "required": [
            "businessId",
            "name",
            "address1",
            "address2",
            "postalcode",
            "city",
            "state",
            "country",
            "email",
            "phone",
            "jurisdiction"
          ],
          "properties": {
            "businessId": {
              "type": "string",
              "default": ""
            },
            "name": {
              "type": "string",
              "default": ""
            },
            "address1": {
              "type": "string",
              "default": ""
            },
            "address2": {
              "type": "string",
              "default": ""
            },
            "postalcode": {
              "type": "string",
              "default": ""
            },
            "city": {
              "type": "string",
              "default": ""
            },
            "state": {
              "type": "string",
              "default": ""
            },
            "country": {
              "type": "string",
              "default": ""
            },
            "email": {
              "type": "string",
              "default": ""
            },
            "phone": {
              "type": "string",
              "default": ""
            },
            "jurisdiction": {
              "type": "string",
              "default": ""
            }
          }
        },
        "cert": {
          "type": "object",
          "required": [
            "x5u"
          ],
          "properties": {
            "x5u": {
              "type": "string",
              "default": ""
            }
          }
        },
        "serviceUrls": {
          "type": "object",
          "required": [
            "domain",
            "libraryDomain",
            "linkingUri",
            "linkingRedirectUri",
            "objectionUri",
            "notificationUri"
          ],
          "properties": {
            "domain": {
              "type": "string",
              "default": ""
            },
            "libraryDomain": {
              "type": "string",
              "default": ""
            },
            "linkingUri": {
              "type": "string",
              "default": ""
            },
            "linkingRedirectUri": {
              "type": "string",
              "default": ""
            },
            "objectionUri": {
              "type": "string",
              "default": ""
            },
            "notificationUri": {
              "type": "string",
              "default": ""
            }
          }
        }
      }
    },
    "isDescribedAt": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "datasetId",
          "description",
          "datasetSchema",
          "dataStructureSpecification",
          "distribution",
          "dataMapping"
        ],
        "properties": {
          "datasetId": {
            "type": "string",
            "default": ""
          },
          "description": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "locale",
                "description",
                "keyword"
              ],
              "properties": {
                "locale": {
                  "type": "string",
                  "default": ""
                },
                "description": {
                  "type": "string",
                  "default": ""
                },
                "keyword": {
                  "type": "array",
                  "items": {
                    "type": "string",
                    "default": ""
                  }
                }
              }
            }
          },
          "datasetSchema": {
            "type": "object",
            "required": [
              "context",
              "type",
              "id"
            ],
            "properties": {
              "context": {
                "type": "string",
                "default": ""
              },
              "type": {
                "type": "string",
                "default": ""
              },
              "id": {
                "type": "string",
                "default": ""
              }
            }
          },
          "dataStructureSpecification": {
            "type": "string",
            "default": ""
          },
          "distribution": {
            "type": "object",
            "required": [
              "distributionId",
              "accessUrl",
              "description",
              "format"
            ],
            "properties": {
              "distributionId": {
                "type": "string",
                "default": ""
              },
              "accessUrl": {
                "type": "string",
                "default": ""
              },
              "description": {
                "type": "array",
                "items": {
                  "type": "object",
                  "required": [
                    "locale",
                    "description"
                  ],
                  "properties": {
                    "locale": {
                      "type": "string",
                      "default": ""
                    },
                    "description": {
                      "type": "string",
                      "default": ""
                    }
                  }
                }
              },
              "format": {
                "type": "string",
                "default": ""
              }
            }
          },
          "dataMapping": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "property",
                "conceptId",
                "name",
                "type",
                "required",
                "sensitive"
              ],
              "properties": {
                "property": {
                  "type": "string",
                  "default": ""
                },
                "conceptId": {
                  "type": "string",
                  "default": ""
                },
                "name": {
                  "type": "string",
                  "default": ""
                },
                "type": {
                  "type": "string",
                  "default": ""
                },
                "required": {
                  "type": "integer",
                  "default": 0
                },
                "sensitive": {
                  "type": "integer",
                  "default": 0
                }
              }
            }
          }
        }
      }
    },
    "processingBases": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "purposeId",
          "purposeName",
          "legalBasis",
          "purposeCategory",
          "processingCategories",
          "description",
          "requiredDatasets",
          "storage",
          "recipients",
          "shareWith",
          "obligations",
          "policyRef"
        ],
        "properties": {
          "purposeId": {
            "type": "string",
            "default": ""
          },
          "purposeName": {
            "type": "string",
            "default": ""
          },
          "legalBasis": {
            "type": "string",
            "default": ""
          },
          "purposeCategory": {
            "type": "string",
            "default": ""
          },
          "processingCategories": {
            "type": "array"
          },
          "description": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "locale",
                "title",
                "description",
                "descriptionUrl",
                "iconUrl"
              ],
              "properties": {
                "locale": {
                  "type": "string",
                  "default": ""
                },
                "title": {
                  "type": "string",
                  "default": ""
                },
                "description": {
                  "type": "string",
                  "default": ""
                },
                "descriptionUrl": {
                  "type": "string",
                  "default": ""
                },
                "iconUrl": {
                  "type": "string",
                  "default": ""
                }
              }
            }
          },
          "requiredDatasets": {
            "type": "array",
            "items": {
              "type": "string",
              "default": ""
            }
          },
          "storage": {
            "type": "object",
            "required": [
              "location",
              "duration"
            ],
            "properties": {
              "location": {
                "type": "string",
                "default": ""
              },
              "duration": {
                "type": "string",
                "default": ""
              }
            }
          },
          "recipients": {
            "type": "array"
          },
          "shareWith": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "orgName",
                "businessType"
              ],
              "properties": {
                "orgName": {
                  "type": "string",
                  "default": ""
                },
                "businessType": {
                  "type": "string",
                  "default": ""
                }
              }
            }
          },
          "obligations": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "event",
                "activity"
              ],
              "properties": {
                "event": {
                  "type": "string",
                  "default": ""
                },
                "activity": {
                  "type": "string",
                  "default": ""
                }
              }
            }
          },
          "policyRef": {
            "type": "string",
            "default": ""
          }
        }
      }
    }
  }
}

=== OPSILab/Cape/cape-services-examples/ife/service_descriptions/M1876-Kindergarten_Registration.json
{
  "serviceId": "M1876",
  "name": "Kindergarten Registration",
  "identifier": "http://localhost:8080/IFE/kindergaten_registration.html",
  "issued": "",
  "createdByUserId": "",
  "serviceDescriptionVersion": "v0.3",
  "serviceIconUrl": "https://i.pinimg.com/564x/a6/b8/d2/a6b8d20a0e2f36df01382439a2e8a932.jpg",
  "status": "Completed",
  "supportedProfiles": [
    "consenting",
    "3rd party re-use",
    "notification",
    "objection"
  ],
  "spatial": "ITA-Italy",
  "lifeEvent": "Starting education",
  "businessEvent": "",
  "sector": [],
  "type": [
    "10.4 - Family and children"
  ],
  "thematicArea": [
    "10.4 - Family and children"
  ],
  "language": [
    "en",
    "fr-fr",
    "it"
  ],
  "hasCompetentAuthority": {
    "prefLabel": "Municipality Of",
    "spatial": "ITA-Italy"
  },
  "humanReadableDescription": [
    {
      "locale": "en",
      "description": "E-service form for kindergaten Registration ",
      "keyword": []
    }
  ],
  "serviceInstance": {
    "serviceProvider": {
      "businessId": "",
      "name": "",
      "address1": "",
      "address2": "",
      "postalcode": "",
      "city": "",
      "state": "",
      "country": "",
      "email": "",
      "phone": "",
      "jurisdiction": ""
    },
    "cert": {
      "x5u": ""
    },
    "serviceUrls": {
      "domain": "https://localhost:8080/",
      "libraryDomain": "",
      "linkingUri": "",
      "linkingRedirectUri": "",
      "objectionUri": "",
      "notificationUri": ""
    },
    "dataController": {
      "piiController": "Controller Name",
      "onBehalf": false,
      "org": "PA NAme",
      "contact": "contact Name",
      "address": "address 123",
      "email": "mail@pa.it",
      "phone": "123"
    }
  },
  "isDescribedAt": [
    {
      "datasetId": "Contacts",
      "description": [
        {
          "locale": "en",
          "description": "Contact Info",
          "keyword": []
        }
      ],
      "datasetSchema": {
        "context": "",
        "type": "",
        "id": ""
      },
      "dataStructureSpecification": "",
      "distribution": {
        "distributionId": "",
        "accessUrl": "",
        "description": [],
        "format": ""
      },
      "dataMapping": [
        {
          "property": "AventeTitolo_Fax",
          "conceptId": "fax_number_for_support",
          "name": "Fax Number",
          "type": "text",
          "required": 0,
          "sensitive": 0
        },
        {
          "property": "AventeTitolo_EMail",
          "conceptId": "personal_email",
          "name": "Email",
          "type": "text",
          "required": 0,
          "sensitive": 0
        },
        {
          "property": "AventeTitolo_EMailPEC",
          "conceptId": "personal_other_email",
          "name": "Other Email",
          "type": "text",
          "required": 0,
          "sensitive": 0
        },
        {
          "property": "AventeTitolo_Telefono",
          "conceptId": "phone_number",
          "name": "Phone Number",
          "type": "text",
          "required": 0,
          "sensitive": 0
        }
      ]
    },
    {
      "datasetId": "ChildInfo",
      "description": [
        {
          "locale": "en",
          "description": "Child info",
          "keyword": []
        }
      ],
      "datasetSchema": {
        "context": "",
        "type": "",
        "id": ""
      },
      "dataStructureSpecification": "",
      "distribution": {
        "distributionId": "",
        "accessUrl": "",
        "description": [],
        "format": ""
      },
      "dataMapping": [
        {
          "property": "AventeTitolo_EnteProvv",
          "conceptId": "child_custodial_body",
          "name": "Child Custodial Body",
          "type": "text",
          "required": 1,
          "sensitive": 0
        },
        {
          "property": "AventeTitolo_NumProt",
          "conceptId": "child_custodial_protocol",
          "name": "Child Custodial Protocol",
          "type": "text",
          "required": 1,
          "sensitive": 0
        },
        {
          "property": "AventeTitolo_Data",
          "conceptId": "child_custodial_date",
          "name": "Child Custodial Date",
          "type": "text",
          "required": 1,
          "sensitive": 0
        },
        {
          "property": "Name",
          "conceptId": "preferred_first_name",
          "name": "First Name",
          "type": "text",
          "required": 1,
          "sensitive": 0
        },
        {
          "property": "Sex",
          "conceptId": "birth_certificate_sex",
          "name": "Sex",
          "type": "text",
          "required": 1,
          "sensitive": 0
        },
        {
          "property": "birth",
          "conceptId": "birthday_birthday",
          "name": "Birthday",
          "type": "text",
          "required": 1,
          "sensitive": 0
        }
      ]
    },
    {
      "datasetId": "Father",
      "description": [
        {
          "locale": "en",
          "description": "Father Information",
          "keyword": []
        }
      ],
      "datasetSchema": {
        "context": "",
        "type": "",
        "id": ""
      },
      "dataStructureSpecification": "",
      "distribution": {
        "distributionId": "",
        "accessUrl": "",
        "description": [],
        "format": ""
      },
      "dataMapping": [
        {
          "property": "Parametri_TipoLavoroPadre",
          "conceptId": "work_industry",
          "name": "Work Industry",
          "type": "text",
          "required": 1,
          "sensitive": 0
        },
        {
          "property": "Parametri_AziendaLavoroPadre",
          "conceptId": "work_company",
          "name": "Work Company",
          "type": "text",
          "required": 1,
          "sensitive": 0
        },
        {
          "property": "Parametri_ComuneAziendaLavoroPadre",
          "conceptId": "work_current_employer_city",
          "name": "Work City",
          "type": "text",
          "required": 1,
          "sensitive": 0
        },
        {
          "property": "Parametri_ProvAziendaLavoroPadre",
          "conceptId": "work_current_employer_province",
          "name": "Work Province",
          "type": "text",
          "required": 1,
          "sensitive": 0
        },
        {
          "property": "Parametri_IndirizzoAziendaLavoroPadre",
          "conceptId": "work_current_employer_address",
          "name": "Work Address",
          "type": "text",
          "required": 1,
          "sensitive": 0
        },
        {
          "property": "Parametri_CivicoAziendaLavoroPadre",
          "conceptId": "work_current_employer_street_number",
          "name": "Work Post Code",
          "type": "text",
          "required": 1,
          "sensitive": 0
        },
        {
          "property": "Parametri_CapAziendaLavoroPadre",
          "conceptId": "work_current_employer_post_code",
          "name": "Work Post Code",
          "type": "text",
          "required": 1,
          "sensitive": 0
        },
        {
          "property": "Parametri_TelAziendaLavoroPadre",
          "conceptId": "work_current_employer_phone",
          "name": "Work Phone",
          "type": "text",
          "required": 1,
          "sensitive": 0
        },
        {
          "property": "Parametri_EmailAziendaLavoroPadre",
          "conceptId": "work_current_employer_email",
          "name": "Work Email",
          "type": "text",
          "required": 1,
          "sensitive": 0
        },
        {
          "property": "Parametri_AgenziaEntratePadre",
          "conceptId": "work_current_employer_revenue_agency",
          "name": "Work Revenue Agency",
          "type": "text",
          "required": 1,
          "sensitive": 0
        },
        {
          "property": "name",
          "conceptId": "preferred_first_name",
          "name": "First Name",
          "type": "text",
          "required": 1,
          "sensitive": 0
        },
        {
          "property": "lastname",
          "conceptId": "preferred_last_name",
          "name": "Last Name",
          "type": "text",
          "required": 1,
          "sensitive": 0
        }
      ]
    },
    {
      "datasetId": "Mother",
      "description": [
        {
          "locale": "en",
          "description": "Mother Info",
          "keyword": []
        }
      ],
      "datasetSchema": {
        "context": "",
        "type": "",
        "id": ""
      },
      "dataStructureSpecification": "",
      "distribution": {
        "distributionId": "",
        "accessUrl": "",
        "description": [],
        "format": ""
      },
      "dataMapping": [
        {
          "property": "Name",
          "conceptId": "preferred_first_name",
          "name": "First Name",
          "type": "text",
          "required": 1,
          "sensitive": 0
        },
        {
          "property": "lastname",
          "conceptId": "preferred_last_name",
          "name": "Last Name",
          "type": "text",
          "required": 1,
          "sensitive": 0
        },
        {
          "property": "Parametri_PIVAMadre",
          "conceptId": "work_current_employer_vat",
          "name": "Work VAT",
          "type": "text",
          "required": 1,
          "sensitive": 0
        },
        {
          "property": "Parametri_TipoLavoroMadre",
          "conceptId": "work_industry",
          "name": "Work Industry",
          "type": "text",
          "required": 1,
          "sensitive": 0
        },
        {
          "property": "Parametri_AziendaLavoroMadre",
          "conceptId": "work_company",
          "name": "Work Company",
          "type": "text",
          "required": 1,
          "sensitive": 0
        },
        {
          "property": "Parametri_ComuneAziendaLavoroMadre",
          "conceptId": "work_current_employer_city",
          "name": "Work City",
          "type": "text",
