=== OPSILab/Cape/cape-server/service-registry/src/main/resources/schema/serviceEntry.json
{
	"definitions": {
		"humanReadableDescription": {
			"type": "array",
			"description": "Array of localized textual descriptions.",
			"format": "tabs",
			"items": {
				"type": "object",
				"title": "Textual Description",
				"headerTemplate": "Locale ({{ self.locale }}) ",
				"options": {
					"collapsed": false
				},
				"properties": {
					"locale": {
						"type": "string",
						"description": "Language used in textual description, in ISO 639-1 format.",
						"watch": {
							"possible_langs": "root.language"
						},
						"enumSource": "possible_langs"
					},
					"description": {
						"type": "string",
						"description": "Textual description of the Service in specified language.",
						"format": "textarea"
					},
					"keywords": {
						"type": "array",
						"title": "Keywords",
						"description": "Keyword tags related to textual description.",
						"uniqueItems": true,
						"format": "select",
						"options": {
							"tags": true
						},
						"items": {
							"type": "string",
							"title": "Tag",
							"id": "arr_item"
						}
					}
				},
				"required": [
					"locale",
					"description"
				]
			}
		}
	},
	"title": "ServiceEntry",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "http://example.com/root.json",
	"type": "object",
	"required": [
		"serviceId",
		"name",
		"createdByUserId",
		"serviceDescriptionVersion",
		"supportedProfiles",
		"type",
		"thematicArea",
		"language",
		"hasCompetentAuthority",
		"humanReadableDescription",
		"serviceInstance",
		"isDescribedAt",
		"processingBases",
		"role"
	],
	"format": "categories",
	"properties": {
		"serviceId": {
			"type": "string",
			"title": "Service ID",
			"default": "",
			"description": "Unique ID for the service.",
			"minLength": 3
		},
		"name": {
			"type": "string",
			"title": "Service Name",
			"minLength": 1,
			"description": "Service Name"
		},
		"identifier": {
			"type": "string",
			"title": "Service Identifier",
			"description": "Service URI if exists, otherwise the same of Service Id."
		},
		"issued": {
			"type": "string",
			"format": "date-time",
			"title": "Issued at",
			"description": "Timestamp of the Service creation."
		},
		"createdByUserId": {
			"type": "string",
			"title": "Created by User Id",
			"description": "User Id of Service Editor (e.g. Data Controller).",
			"minLength": 3
		},
		"serviceDescriptionVersion": {
			"type": "string",
			"title": "Service Description version",
			"description": "Service description version number."
		},
		"serviceDescriptionSignature": {
			"title": "Service Description Signature",
			"type": "string",
			"description": "JWS signature (signed with Service private key) of the Service Description"
		},
		"serviceIconUrl": {
			"type": "string",
			"title": "Service Icon Url",
			"description": "URL pointing to Service Icon file"
		},
		"status": {
			"type": "string",
			"title": "Service Description status",
			"description": "Status of Service Description (Allowed values: *Completed*, *Deprecated*, *UnderDevelopment*, *Withdrawn*)",
			"default": "Completed",
			"enum": [
				"Completed",
				"Deprecated",
				"UnderDevelopment",
				"WithDrawn"
			]
		},
		"supportedProfiles": {
			"type": "array",
			"title": "Supported profiles",
			"description": " Type of Data processing regulation profiles supported by the Service, according to My Data specification (Allowed values: *contract*, *consenting*, *3rd party re-use*, *notification*, *objection*)",
			"default": "Consenting",
			"items": {
				"type": "string",
				"format": "select",
				"enum": [
					"Contract",
					"Consenting",
					"3rd party re-use",
					"Notification",
					"Objection"
				]
			},
			"format": "select2",
			"uniqueItems": true
		},
		"spatial": {
			"title": "Spatial",
			"description": "Geographical Localization of Service",
			"type": "string",
			"format": "select2",
			"options": {
				"grid_columns": 12
			}
		},
		"lifeEvent": {
			"$ref": "./life_event.json"
		},
		"businessEvent": {
			"$ref": "./business_event.json"
		},
		"sector": {
			"$ref": "./sectors.json"
		},
		"type": {
			"$ref": "./types.json"
		},
		"thematicArea": {
			"$ref": "./thematic_area.json"
		},
		"language": {
			"$ref": "./locale.json"
		},
		"hasCompetentAuthority": {
			"title": "Competent Authority",
			"description": "If public Service, link to a Public Organization, which is the responsible Agent for the delivery of the Public Service.",
			"type": "object",
			"properties": {
				"prefLabel": {
					"type": "string",
					"title": "Preferred Label"
				},
				"spatial": {
					"$ref": "#/properties/spatial"
				}
			}
		},
		"humanReadableDescription": {
			"$ref": "#/definitions/humanReadableDescription"
		},
		"serviceInstance": {
			"$ref": "./service_instance.json"
		},
		"isDescribedAt": {
			"$ref": "./is_described_at.json"
		},
		"processingBases": {
			"type": "array",
			"title": "Data Processing Bases",
			"format": "tabs",
			"description": "It collects the different legal basis and requirements for personal data processing according to EU data protection Rules (Art. 6 GDPR). It describes describe different situations where a company or an organisation is allowed to collect or reuse your personal information: contract, legal obligation, vital interest, public interest, legitimate interest and consent",
			"items": {
				"$ref": "./processing_basis.json"
			}
		},
		"role": {
			"type": "string",
			"description": "Role that the Service will have in data processing and related Consents: Sink (Data Requester) or Source (Data Provider) ",
			"enum": [
				"Sink",
				"Source"
			]
		}
	}
}

=== OPSILab/Cape/cape-online-services/src/assets/serviceOnlineGE_2_description.json
{
  "serviceId": "GE_2",
  "name": "Protezione Civile Iscrizione alerta",
  "identifier": "GE_2",
  "issued": "",
  "createdByUserId": "",
  "serviceDescriptionVersion": "1.0",
  "serviceDescriptionSignature": "",
  "serviceIconUrl": "",
  "status": "Completed",
  "supportedProfiles": [
    "Consenting",
    "3rd party re-use",
    "Notification",
    "Objection"
  ],
  "spatial": "ITA-Italy",
  "lifeEvent": "other",
  "businessEvent": "other",
  "sector": [],
  "type": ["01 - General public services"],
  "thematicArea": ["01 - General public services"],
  "language": ["en", "it"],
  "hasCompetentAuthority": {
    "prefLabel": "Genova Smart Services",
    "spatial": "ITA-Italy"
  },
  "humanReadableDescription": [
    {
      "locale": "it",
      "description": "Servizio di info e allerta tramite messagistica e BOT",
      "keywords": []
    }
  ],
  "serviceInstance": {
    "serviceProvider": {
      "businessId": "ENG",
      "name": "Engineering",
      "address1": "Genova",
      "address2": "Genova",
      "postalcode": "00666",
      "city": "Genova",
      "state": "Italy",
      "country": "Italy",
      "email": "genova@genova.it",
      "phone": "1111",
      "jurisdiction": "IT"
    },
    "cert": {
      "x5u": "",
      "x5c": []
    },
    "serviceUrls": {
      "libraryDomain": "http://localhost:8085/cape-service-sdk",
      "loginUri": "http://localhost:4400/pages/services",
      "linkingRedirectUri": "http://localhost:4400",
      "objectionUri": "",
      "notificationUri": ""
    },
    "dataController": {
      "piiController": "",
      "onBehalf": false,
      "org": "",
      "contact": "",
      "address": "",
      "email": "",
      "phone": ""
    }
  },
  "isDescribedAt": [
    {
      "datasetId": "General_01",
      "description": [
        {
          "locale": "it",
          "description": "Dati generali del richiedente (email, indirizzo, telefono)",
          "keyword": []
        }
      ],
      "datasetSchema": {
        "context": "",
        "type": "",
        "id": ""
      },
      "dataStructureSpecification": "",
      "distribution": {
        "distributionId": "",
        "accessUrl": "",
        "description": [],
        "format": ""
      },
      "dataMapping": [
        {
          "property": "email",
          "conceptId": "personal_email",
          "name": "Email",
          "type": "text",
          "required": true
        },
        {
          "property": "phone",
          "conceptId": "phone_number",
          "name": "Phone Number",
          "type": "text",
          "required": false
        },
        {
          "property": "address",
          "conceptId": "previous_address_street",
          "name": "Street Address 1",
          "type": "text",
          "required": false
        }
      ]
    }
  ],
  "processingBases": [
    {
      "purposeId": "PInterest_1",
      "purposeName": "Registrazione Servizio",
      "legalBasis": "Public interest",
      "purposeCategory": "PersonalisedBenefits",
      "processingCategories": ["Collect"],
      "description": [
        {
          "locale": "it",
          "title": "Registrazione Servizio",
          "description": "Raccolta dati per manifestazione d’interesse a registrazione del sistema di allerta",
          "descriptionUrl": "",
          "iconUrl": ""
        }
      ],
      "requiredDatasets": ["General_01"],
      "storage": {
        "location": "Our servers",
        "duration": "Business practices"
      },
      "recipients": ["Ours"],
      "shareWith": [],
      "obligations": [],
      "policyRef": "https://smart.comune.genova.it/privacy",
      "collectionMethod": "Online",
      "termination": ""
    },
    {
      "purposeId": "Reuse_1",
      "purposeName": "Riutilizzo dei dati per altri servizi all'interno della municipalità",
      "legalBasis": "Consent",
      "purposeCategory": "PersonalisedBenefits",
      "processingCategories": ["Collect", "Copy"],
      "description": [
        {
          "locale": "it",
          "title": "Riuso e personalizzazione servizi",
          "description": "I dati salvati potranno essere riutilizzati per la personalizzazione di altri servizi forniti dal comune",
          "descriptionUrl": "",
          "iconUrl": ""
        }
      ],
      "requiredDatasets": ["General_01"],
      "storage": {
        "location": "Our servers",
        "duration": "Stated purpose"
      },
      "recipients": ["Other recipient"],
      "shareWith": [
        {
          "orgName": "SocialMessage Inc.",
          "orgUrl": "",
          "businessType": "Profit",
          "required": false
        }
      ],
      "obligations": [],
      "policyRef": "https://smart.comune.it/privacy",
      "collectionMethod": "Online",
      "termination": ""
    }
  ],
  "role": "Sink"
}

=== OPSILab/Cape/cape-online-services/src/assets/serviceOnlineGE_1_description.json
{
  "serviceId": "GE_1",
  "name": "Iscrizioni servizi 0-6",
  "identifier": "https://www.cape-suite.eu/cape-online-services/pages/services",
  "issued": "",
  "createdByUserId": "",
  "serviceDescriptionVersion": "1.0",
  "serviceDescriptionSignature": "",
  "serviceIconUrl": "",
  "status": "Completed",
  "supportedProfiles": ["Consenting", "3rd party re-use", "Notification", "Objection"],
  "spatial": "ITA-Italy",
  "lifeEvent": "Starting education",
  "businessEvent": "",
  "sector": [],
  "type": ["01 - General public services"],
  "thematicArea": ["01 - General public services"],
  "language": ["en", "it"],
  "hasCompetentAuthority": {
    "prefLabel": "Genova Smart Services",
    "spatial": "ITA-Italy"
  },
  "humanReadableDescription": [
    {
      "locale": "it",
      "description": "Manifestazione d’interesse on line servizi asilo nido ed infanzia 2020",
      "keywords": []
    }
  ],
  "serviceInstance": {
    "serviceProvider": {
      "businessId": "ENG",
      "name": "Engineering",
      "address1": "Genova",
      "address2": "Genova",
      "postalcode": "00666",
      "city": "Genova",
      "state": "Italy",
      "country": "Italy",
      "email": "genova@genova.it",
      "phone": "1111",
      "jurisdiction": "IT"
    },
    "cert": {
      "x5u": "",
      "x5c": []
    },
    "serviceUrls": {
      "libraryDomain": "http://service-sdk:8085/cape-service-sdk",
      "loginUri": "https://www.cape-suite.eu/cape-online-services/pages/services",
      "linkingRedirectUri": "https://www.cape-suite.eu/cape-online-services",
      "objectionUri": "",
      "notificationUri": ""
    },
    "dataController": {
      "piiController": "",
      "onBehalf": false,
      "org": "",
      "contact": "",
      "address": "",
      "email": "",
      "phone": ""
    }
  },
  "isDescribedAt": [
    {
      "datasetId": "General_01",
      "description": [
        {
          "locale": "it",
          "description": "Dati generali del richiedente (email, indirizzo, telefono)",
          "keyword": []
        }
      ],
      "datasetSchema": {
        "context": "",
        "type": "",
        "id": ""
      },
      "dataStructureSpecification": "",
      "distribution": {
        "distributionId": "",
        "accessUrl": "",
        "description": [],
        "format": ""
      },
      "dataMapping": [
        {
          "property": "email",
          "conceptId": "personal_email",
          "name": "Email",
          "type": "text",
          "required": true
        },
        {
          "property": "phone",
          "conceptId": "phone_number",
          "name": "Phone Number",
          "type": "text",
          "required": false
        },
        {
          "property": "address",
          "conceptId": "previous_address_street",
          "name": "Street Address 1",
          "type": "text",
          "required": false
        }
      ]
    }
  ],
  "processingBases": [
    {
      "purposeId": "PInterest_1",
      "purposeName": "Registrazione Servizio",
      "legalBasis": "Public interest",
      "purposeCategory": "PersonalisedBenefits",
      "processingCategories": ["Collect"],
      "description": [
        {
          "locale": "it",
          "title": "Registrazione Servizio",
          "description": "Raccolta dati per manifestazione d’interesse on line servizi asilo nido ed infanzia 2020",
          "descriptionUrl": "",
          "iconUrl": ""
        }
      ],
      "requiredDatasets": ["General_01"],
      "storage": {
        "location": "Our servers",
        "duration": "Business practices"
      },
      "recipients": ["Ours"],
      "shareWith": [],
      "obligations": [],
      "policyRef": "https://smart.comune.genova.it/privacy",
      "collectionMethod": "Online",
      "termination": ""
    },
    {
      "purposeId": "Reuse_1",
      "purposeName": "Riutilizzo dei dati per altri servizi all'interno della municipalità",
      "legalBasis": "Consent",
      "purposeCategory": "PersonalisedBenefits",
      "processingCategories": ["Collect", "Copy"],
      "description": [
        {
          "locale": "it",
          "title": "Riuso e personalizzazione servizi",
          "description": "I dati salvati potranno essere riutilizzati per la personalizzazione di altri servizi forniti dal comune",
          "descriptionUrl": "",
          "iconUrl": ""
        }
      ],
      "requiredDatasets": ["General_01"],
      "storage": {
        "location": "Our servers",
        "duration": "Stated purpose"
      },
      "recipients": ["Other recipient"],
      "shareWith": [
        {
          "orgName": "Mensa comunale ",
          "orgUrl": "",
          "businessType": "Profit",
          "required": false
        }
      ],
      "obligations": [],
      "policyRef": "https://smart.comune.it/privacy",
      "collectionMethod": "Online",
      "termination": ""
    }
  ],
  "role": "Sink"
}

=== OPSILab/Cape/cape-playground/src/assets/My Wellness Service Description.json
{
	"serviceId": "MYW20",
	"name": "My Wellness",
	"identifier": "http://localhost:82/cape-playground/pages/services/my-wellness",
	"issued": "2020-18-06T13:48:00Z",
	"createdByUserId": "Cape Developers",
	"serviceDescriptionVersion": "1.0",
	"serviceDescriptionSignature": "",
	"serviceIconUrl": "http://localhost:82/cape-playground/my-wellness/favicon.ico",
	"status": "Completed",
	"supportedProfiles": [
		"Consenting"
	],
	"spatial": "ITA-Italy",
	"lifeEvent": "other",
	"businessEvent": "other",
	"sector": [
		"other"
	],
	"type": [
		"other"
	],
	"thematicArea": [
		"other"
	],
	"language": [
		"it",
		"en"
	],
	"hasCompetentAuthority": {
		"prefLabel": "Engineering",
		"spatial": "ITA-Italy"
	},
	"humanReadableDescription": [
		{
			"locale": "en",
			"description": "The My Wellness Service provides useful suggestions about your diet and workouts, based on your hystorical cholesterol and body weight trends. These measurements will be retrieved from a thir party service, called My Measurements.",
			"keywords": []
		},
		{
			"locale": "it",
			"description": "Il Servizio My Wellness fornisce utili suggerimenti sulla tua dieta e i workouts, basati sull'andamento storico del tuo colesterolo e peso corporeo. Tali misurazioni verranno recuperate da un servizio terzo, chiamato My Measurements.",
			"keywords": []
		}
	],
	"serviceInstance": {
		"serviceProvider": {
			"businessId": "ENG",
			"name": "Engineering",
			"address1": "",
			"address2": "",
			"postalcode": "",
			"city": "",
			"state": "",
			"country": "",
			"email": "",
			"phone": "",
			"jurisdiction": "EU"
		},
		"cert": {
			"x5u": "",
			"x5c": []
		},
		"serviceUrls": {
			"domain": "http://localhost82/cape-playground",
			"libraryDomain": "http://service-sdk:8085/cape-service-sdk",
			"loginUri": "http://localhost:82/cape-playground/pages/services/my-wellness",
			"linkingUri": "http://service-sdk:8085/cape-service-sdk/api/v2/slr/linking",
			"linkingRedirectUri": "http://localhost:82/cape-playground",
			"objectionUri": "",
			"notificationUri": ""
		},
		"dataController": {
			"piiController": "John Doe",
			"onBehalf": false,
			"org": "ENG",
			"contact": "",
			"address": "",
			"email": "johndoe@example.com",
			"phone": "+39222222",
			"operatorName": "John Doe"
		}
	},
	"isDescribedAt": [
		{
			"datasetId": "D_1",
			"description": [
				{
					"locale": "en",
					"description": "This dataset represents data used for the MyCholesterol purpose",
					"keyword": []
				},
				{
					"locale": "it",
					"description": "Questo dataset rappresenta i dati utilizzati per il purpose MyCholesterol",
					"keyword": []
				}
			],
			"datasetSchema": {
				"context": "",
				"type": "",
				"id": ""
			},
			"dataStructureSpecification": "",
			"distribution": {
				"distributionId": "",
				"accessUrl": "",
				"description": [],
				"format": ""
			},
			"dataMapping": [
				{
					"property": "sex",
					"conceptId": "personal_details_sex",
					"name": "Gender",
					"type": "text",
					"required": false
				},
				{
					"property": "cholesterol",
					"conceptId": "cholesterol_total",
					"name": "Blood Cholesterol",
					"type": "text",
					"required": true
				},
				{
					"property": "age",
					"conceptId": "personal_details_age",
					"name": "Age",
					"type": "text",
					"required": false
				}
			]
		},
		{
			"datasetId": "D_2",
			"description": [
				{
					"locale": "en",
					"description": "This dataset represents data used for the MyWeight purpose",
					"keyword": []
				},
				{
					"locale": "it",
					"description": "Questo dataset rappresenta i dati utilizzati per il purpose MyWeight",
					"keyword": []
				}
			],
			"datasetSchema": {
				"context": "",
				"type": "",
				"id": ""
			},
			"dataStructureSpecification": "",
			"distribution": {
				"distributionId": "",
				"accessUrl": "",
				"description": [],
				"format": ""
			},
			"dataMapping": [
				{
					"property": "sex",
					"conceptId": "personal_details_sex",
					"name": "Gender",
					"type": "text",
					"required": false
				},
				{
					"property": "weight",
					"conceptId": "personal_details_body_weight",
					"name": "Body Weight",
					"type": "text",
					"required": true
				},
				{
					"property": "age",
					"conceptId": "personal_details_age",
					"name": "Age",
					"type": "text",
					"required": false
				}
			]
		}
	],
	"processingBases": [
		{
			"purposeId": "1",
			"purposeName": "MyCholesterol",
			"legalBasis": "Consent",
			"purposeCategory": "1 - Core Function",
			"processingCategories": [
				"Aggregate",
				"Collect",
				"Derive",
				"Query"
			],
			"description": [
				{
					"locale": "en",
					"title": "MyCholesterol",
					"description": "This purpose enables to visualize your customized diet programs, based on the historical measurements of your blood cholesterol, in addition to your age and gender. These measurements will be retrieved from a third party service, called MyMeasure.",
					"descriptionUrl": "",
					"iconUrl": ""
				},
				{
					"locale": "it",
					"title": "MyCholesterol",
					"description": "Questo purpose permette di visualizzare dei programmi di dieta personalizzati, basati sullo storico delle misurazioni del tuo colesterolo nel sangue, oltre alla tua età e sesso. Tali misurazioni verrranno recuperate da un servizio terzo, chiamato MyMeasure.",
					"descriptionUrl": "",
					"iconUrl": ""
				}
			],
			"requiredDatasets": [
				"D_1"
			],
			"storage": {
				"location": "Controller servers",
				"duration": "Business practices"
			},
			"recipients": [
				"Ours"
			],
			"shareWith": [
				{
					"orgName": "Health Organization",
					"orgUrl": "www.example.com",
					"businessType": "Profit",
					"required": true
				},
				{
					"orgName": "Optional Organization",
					"orgUrl": "www.example.com",
					"businessType": "No profit",
					"required": false
				}
			],
			"obligations": [],
			"policyRef": "http://mywellness.com/policy",
			"collectionMethod": "Automatic aggregation",
			"termination": "None"
		},
		{
			"purposeId": "2",
			"purposeName": "MyWeight",
			"legalBasis": "Consent",
			"purposeCategory": "1 - Core Function",
			"processingCategories": [
				"Aggregate",
				"Analyse",
				"Collect",
				"Derive",
				"Query"
			],
			"description": [
				{
					"locale": "en",
					"title": "MyWeight",
					"description": "This purpose enables to visualize your customized workout programs, based on the historical measurements of your body weight, in addition to your age and gender. These measurements will be retrieved from a third party service, called MyMeasure.",
					"descriptionUrl": "",
					"iconUrl": ""
				},
				{
					"locale": "it",
					"title": "MyWeight",
					"description": "Questo purpose permette di visualizzare dei programmi di workout personalizzati, basati sullo storico delle misurazioni del tuo peso corporeo, oltre alla tua età e sesso. Tali misurazioni verrranno recuperate da un servizio terzo, chiamato MyMeasure.",
					"descriptionUrl": "",
					"iconUrl": ""
				}
			],
			"requiredDatasets": [
				"D_2"
			],
			"storage": {
				"location": "Controller servers",
				"duration": "Business practices"
			},
			"recipients": [
				"Ours"
			],
			"shareWith": [
				{
					"orgName": "Health Organization",
					"orgUrl": "http://www.example.com",
					"businessType": "Profit",
					"required": true
				},
				{
					"orgName": "Optional Organization",
					"orgUrl": "www.example.com",
					"businessType": "No profit",
					"required": false
				}
			],
			"obligations": [
				{
					"event": "",
					"activity": ""
				}
			],
			"policyRef": "http://mywellness.com/policy",
			"collectionMethod": "Automatic aggregation",
			"termination": "None"
		}
	],
	"role": "Sink"
}
